### ISSUE TITLE
Merge Prometheus-SLI-Service and Prometheus-service

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/prometheus-service#122]
Currently we maintain two different services to interact with Prometheus, namely the Prometheus-service and the [Prometheus-SLI-service](https://github.com/keptn-contrib/prometheus-sli-service). 

We should merge the two services into one Prometheus-service to avoid confusion, ease the installation process, and save resources.

**Definition of done**

- [ ] All capabilities of prometheus-sli-service integrated into the prometheus-service
- [ ] Updated documentation
- [ ] Archived the Prometheus SL service

**Comment by jetzlstorfer** [comment]
@rajdas98 please have a look here

**Comment by rajdas98** [comment]
Thanks, Please assign this issue to me

**Comment by jetzlstorfer** [comment]
Related PR #132
