### ISSUE TITLE
Allow configuration of scrape_interval as Helm Value / Environment value

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/prometheus-service#133]
Currently, the scrape interval is set to 1 minute.
I am not sure if that is because the global scrape interval is set to 1 minute or if the prometheus-service is setting this.

As an improvement, it would be great to make the scrape interval configurable, for example via the ENV variables of the service.
This would allow to change the scrape interval for Keptn managed scrape jobs easily.

**Comment by christian-kreuzberger-dtx** [comment]
*Definition of Done*:

* Scrape Interval can be configured within the helm chart as a helm value, and is applied in the scrape config when calling `keptn configure monitoring`
