### ISSUE TITLE
Lack of precision when fetching SLIs from prometheus due to the scrape interval

### ISSUE THREAD

**Issue by ngauje** [keptn-contrib/prometheus-service#179]
Hello,

Since prometheus is pull based, it fetch metrics at a regular interval ("scrape interval").
So when the service is responding to `sh.keptn.event.get-sli.triggered`, if prometheus is not up-to-date (ie. the last scraping occurs before the end of the load test) you will fetch incomplete results.

To illustrate, I've created a SLI of _number of requests_ to count all requests made during the load test (1000 req), and I've set an objective (>=1000) on it.

On the first release I missed the target : 667 < 1000
In prometheus, I have however more than 1000 requests recorded.
I guess it's because on short load campaign, the SLI is returned before prometheus scraped all the results of the load timeframe.

So I put a timer on the jmeter test plan to lett some time for prometheus to fetch all tests results, so when Keptn fetch the SLI, I'm sure that prometheus have up-to-date metrics.
Result: 1035 calls returned

I don't know what is the best way to deal with this, maybe by checking the last scrape timestamp to see if it's > to the "test end" timestamp

Discussion started here : https://keptn.slack.com/archives/CNRCGFU3U/p1632517239213700

**Comment by ngauje** [comment]
Those 2 issues are somehow related since they are talking about the `scrape_interval`, but being able to configure it will not solve my issue.
I think that, at least Keptn should be able to fetch the scrape_interval so it can take it in account when fetching results.
But is it the responsability of Keptn to change this parameter?

**Comment by christian-kreuzberger-dtx** [comment]
> I think that, at least Keptn should be able to fetch the scrape_interval so it can take it in account when fetching results.
> But is it the responsability of Keptn to change this parameter?

Not Keptn per-say, but the prometheus-service.

I ran into the same issue, see https://github.com/keptn-contrib/prometheus-service/issues/198

Basically I'm missing data in the beginning of the test, which lead to the wrong data being returned.

**Comment by christian-kreuzberger-dtx** [comment]
Fixed with #199
