### ISSUE TITLE
Improve prometheus-server and alert-manager reloading logic

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/prometheus-service#240]
Right now every time we run `keptn configure monitoring prometheus --project=... --service=...` we end up doing multiple things:

* Creating/updating scrape jobs for each stage and each service (and we don't check whether it's blue-green or direct deployed, so we end up creating three scrape jobs per service and stage)
* Creating/updating alerts based on SLOs for each stage and each service

Both require prometheus-server and alert-manager to be reloaded, which we do via killing the respective pods:
https://github.com/keptn-contrib/prometheus-service/blob/44488abcea2cd4ef4323e288dfc6fe3833099f93/eventhandling/configureEvent.go#L137-L145

I believe this behaviour could be optimized.

**First of all**, we need to figure out why we have to kill pods, when prometheus has a configmap-reloader active?

**Second**, it seems to be also doable by manually creating a request to `http://127.0.0.1:9090{{ .Values.server.prefixURL }}/-/reload` on prometheus-server (a similar request might be possible for alert-manager)

# Definition of Done

- [ ] Reloading configuration of prometheus-server and alert-manager works without killing pods (either via API Call or automatically via configmap reloader)
- [ ] Code for deleting pods is removed
- [ ] Remove rolebinding for deleting pods in monitoring namespace in deploy/role.yaml

**Comment by Paolo-Chila** [comment]
started hacking a possible solution on a [refactor branch](https://github.com/keptn-contrib/prometheus-service/compare/refactor/user-prometheus-management-api), (i.e. it's not yet production ready but it should help validate and refine the concept)
