### ISSUE TITLE
Helm Chart previews: Stop double compression of GitHub Actions artifacts to simplify installation

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn-contrib/prometheus-service#249]
As a Keptn user, I want to easily install preview versions of the Prometheus service. I would like to reference preview artifact URLs in the `helm install` command

Starting from 0.7.2, the installation is managed via Helm. There is also a GitHub Actions CD workflow that produces preview builds for master branch and publishes them as artifacts:

* Installation CLI call: `helm install -n keptn prometheus-service https://github.com/keptn-contrib/prometheus-service/releases/download/0.7.2/prometheus-service-0.7.2.tgz --wait`
* Preview artifact location example: https://github.com/keptn-contrib/prometheus-service/actions/runs/1633249966

## Expected behavior

The preview chart artifact can be referenced in `helm install` by URL. Bonus points for extra quality of life features in Keptn CLI

## Actual behavior

Unfortunately the publishing step adds additional ZIP compression for the produced Tar.gz, and hence an additional step is required to retrieve he archived artifact

```
With the provided path, there will be 1 file uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "helm-charts" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 5055 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!

The raw size of all the files that were specified for upload is 5055 bytes
The size of all the files that were uploaded is 5055 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

Artifact helm-charts has been successfully uploaded!
```

## References

* Slack conversation: https://keptn.slack.com/archives/CNRCGFU3U/p1641814380035900?thread_ts=1641734428.030400&cid=CNRCGFU3U

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

I appreciate the idea, but there are several limitations of GH actions here.

1. You cannot use `helm install` and reference an artifact from an action run (for this you need to be authenticated with GH)
2. You can only store the artifact within a .zip file, so I cannot just provide a `.tgz` file

The only way around this is to use GitHub releases, but this would require nightly releases which is not something we want.

For now, our recommendation is as follows:

1. If you need something form a PR/branch, download the zip file and extract it, then install/use it locally.
2. If you need to test latest development changes locally, use `skaffold run` from the root folder of this project.

**Comment by christian-kreuzberger-dtx** [comment]
Closing this as there has it is a GH issue, and not a prometheus-service issue.
