### ISSUE TITLE
Refactor code in more manageable files and packages

### ISSUE THREAD

**Issue by pchila** [keptn-contrib/prometheus-service#251]
At the moment the code for main server loop, event handling, prometheus interaction and k8s api calls is all bunched together in big files and functions, for example:

https://github.com/keptn-contrib/prometheus-service/blob/6c6e22b0b9e6c52e6fbd079e084f29b704f9cabe/main.go#L129-425

https://github.com/keptn-contrib/prometheus-service/blob/6c6e22b0b9e6c52e6fbd079e084f29b704f9cabe/eventhandling/configureEvent.go

It would make the code more readable and improve testability if we can separate the logic in different package by concern (k8s, prometheus, event handling and so on...) and put appropriate interfaces in place for interactions between packages.

# Definition of Done

- [ ] Break up big files and functions in more manageable chunks in separate packages
- [ ] Write unit tests in the new packages mocking the interfaces defined for dependencies living outside of a given package
- [ ] Make main a small file containing only setup code (e.g. reading environment and storing/passing configuration objects, instantiating necessary objects, setup signal/http handlers etc.) and main HTTP server loop.

If this proves to be too big  we can perhaps handle iteratively with multiple PRs

**Comment by christian-kreuzberger-dtx** [comment]
Some refactoring has been done in #267 and #264
