### ISSUE TITLE
Provide a way to apply the correct rolebinding in prometheus namespace as part of helm install

### ISSUE THREAD

**Issue by pchila** [keptn-contrib/prometheus-service#261]
Current installation procedure requires users of `prometheus-service` to add the role and rolebinding contained [role.yaml](https://github.com/keptn-contrib/prometheus-service/blob/a41d9c0893974a884ae94f8296b5944c84a6f43f/deploy/role.yaml) as a separate step after installing prometheus service using helm.
This is because the current helm installation procedure would not know in which namespace to place the Role and RoleBinding.

We can improve the process (and reduce the chances that people will skip the role installation) by including it in the helm chart and providing users with the possibility of installing everything with a single command. 
Ideally it should be possible to:
- do not install the role (same case as today, it requires the user to manually give the necessary permission to the prometheus service)
- autodetect where prometheus is running in the cluster and install the role there (we can do this using the [helm lookup function](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function))
- manually specify a namespace where the role will be installed during `helm install`

Default behaviour will probably depend on what is currently the most common case but the autodetect feature should help reduce the mistakes in setup phase and improve the general user experience

**Comment by christian-kreuzberger-dtx** [comment]
Was done in #328
