### ISSUE TITLE
Not able to configure prometheus-service in a multi-cluster setup

### ISSUE THREAD

**Issue by AndreasLudviksen** [keptn-contrib/prometheus-service#299]
I am running Keptn in an AKS environment.
Keptn version 0.12.0, prometheus-service version 0.7.3
(Also tried 0.13.5 + 0.7.4)

Delivery with 3 clusters (1 control + 2 execution) is working fine, but I am not able to configure prometheus-service in the execution-plane.
Am I supposed to get this service running okay in an execution-plane? 

These are the services running in the control-plane:
![image](https://user-images.githubusercontent.com/14104867/166250978-69ec20d9-ec04-4241-9850-727bf96638d5.png)

These are the services running in the execution-plane:
![image](https://user-images.githubusercontent.com/14104867/166251107-cfcd326d-a413-4a0e-8cf8-6194a68c1664.png)

The distributor seems to start fine, but never receives any events when I run the 'keptn configure monitoring' command:
![image](https://user-images.githubusercontent.com/14104867/166251360-30680291-873a-4bfe-b782-24001ef9108e.png)

When I start the prometheus-service in the control-plane it gets the event and starts doing some work.
I've tried all thinkable configurations in the values-file, currently running this:
![image](https://user-images.githubusercontent.com/14104867/166292566-38688169-581e-44aa-b08a-91fc333bf3cd.png)

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

unfortunately proemtheus-service is not able to run in remote control plane setup. Unfortunately,`values.yaml` suggests so, but it's only there for "conformity" reasons.

**Comment by AndreasLudviksen** [comment]
Hi,

Thank you for your answer.
Are you saying prometheus + multi-cluster is not supported?
Or is it supported, but prometheus-service needs to run in the control-plane and have access to prometheus in the 'destination' cluster?
Is there a plan to support it?

**Comment by christian-kreuzberger-dtx** [comment]
Closing this as there was no more reply for over 2 months.
