### ISSUE TITLE
Prometheus-Service can not fetch SLIs in the case of remediation sequence

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/prometheus-service#354]
When prometheus-service receives an alert, it usually sends out a Cloud Event like this:
```
{
  "data": {
    "ImpactedEntity": "carts-primary",
    "ProblemID": "",
    "ProblemTitle": "response_time_p90",
    "State": "OPEN",
    "labels": null,
    "project": "sockshop",
    "service": "carts",
    "stage": "production"
    }
  },
  "id": "f446fb69-765a-44fb-afae-6ada0932e060",
  "shkeptncontext": "45f00d73-adde-4cb5-937d-f04642aca846",
  "shkeptnspecversion": "0.2.4",
  "source": "prometheus",
  "specversion": "1.0",
  "time": "2022-08-08T13:35:11.456493663Z",
  "type": "sh.keptn.event.production.remediation.triggered"
}
```
Keptn then receives this remediation.triggered event, and runs the remediation sequence, which eventually sends out a `get-sli.triggered` Cloud Event like this:
```
{
  "contenttype": "application/json",
  "data": {
    "deployment": "",   <--- empty
    "get-sli": {
      "end": "2022-08-09T11:21:00.359Z",
      "indicators": [
        "response_time_p90"
      ],
      "sliProvider": "prometheus",
      "start": "2022-08-09T11:06:00.359Z"
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "production",
    "temporaryData": {
      "distributor": {
        "subscriptionID": ""
      }
    }
  },
  "id": "a58a157f-b844-4010-8a23-3d1ac09d5a4c",
  "shkeptncontext": "2933698c-e150-4f61-b517-40bde889606b",
  "shkeptnspecversion": "0.2.4",
  "source": "lighthouse-service",
  "specversion": "1.0",
  "time": "2022-08-09T11:21:00.650134011Z",
  "gitcommitid": "16d3cfdf5c6e27bbee52241e307d5c25bf54d086",
  "type": "sh.keptn.event.get-sli.triggered"
}
```

Unfortunately, this leads to an invalid query, e.g.:
```
Generated query: /api/v1/query?query=histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="carts-sockshop-production-"}[900s])))&time=1660047293
```

which is created based on the SLI file
```
  response_time_p90: histogram_quantile(0.9, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-$DEPLOYMENT"}[$DURATION_SECONDS])))
```

# Problem

```
job="$SERVICE-$PROJECT-$STAGE-$DEPLOYMENT"
```
gets translated into
```
job="carts-sockshop-production-"
```

but that job does not exist.

# Analysis

We need to add a way such that in this case `$DEPLOYMENT` is available.
In example, we only configure alerts for `primary` deployments:
https://github.com/keptn-contrib/prometheus-service/blob/9ed3eb2f9bd11d2944cae1bf5a028eda9182cb1c/eventhandling/configureEvent.go#L287-L298

In addition, we set the alertingLabel to include `eventData.Service + "-primary"`:
https://github.com/keptn-contrib/prometheus-service/blob/9ed3eb2f9bd11d2944cae1bf5a028eda9182cb1c/eventhandling/configureEvent.go#L357-L363

# Possible Solutions

* We could always infer `$DEPLOYMENT` as `primary` in the case of alerts
* We could read the deployment type from the alertingLabel

**Comment by Raffy23** [comment]
I would prefer a solution that added the deployment type to the alert labels, and use that one to set the `$DEPLOYMENT` placeholder. It may not fix the issue that alerts work for everything since the configure event only works with "primary", but it should fix the current bug.
