### ISSUE TITLE
Optimize installation of Prometheus Monitoring Support to include SLI service

### ISSUE THREAD

**Issue by grabnerandi** [keptn-contrib/prometheus-service#45]
Right now when enabling support for Prometheus a user has to install the Prometheus Service as well as the Prometheus SLI service. installing the Prometheus Service is done via keptn configure monitoring prometheus - yet - there is an additional step to install & configure the Prometheus SLI service

From an end user perspective this is an error prone task. We have seen some users not installing the SLI PRovider as they assumed they already enabled Prometheus support.

I therefore suggest to optimize the installation of Prometheus Monitoring support so that all necessary components are automatically installed and configured

**Comment by christian-kreuzberger-dtx** [comment]
This has been done with the release of prometheus-service 0.6.0 in June 2021.
