### ISSUE TITLE
Metrics get lost if prometheus pod restarts

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/prometheus-service#49]
If the prometheus pod crashes and restarts, all metrics of my services get lost.

A solution might be to use a PVC as a data store instead of keeping it locally in the pod.

**Comment by agrimmer** [comment]
Valid point!
But Keptn should **not** be the tool for managing the Prometheus. 
Instead, the provided Prometheus instance should only be used for demos and tests.

**Comment by jetzlstorfer** [comment]
But this means that the command `keptn configure monitoring prometheus --project=x --service=y` is rendered useless since it only works with the Prometheus that is set up and managed by Keptn. This is not a verified statement but based on what I see from the source code - please correct me if I am wrong.

I would like to configure an (external) Prometheus with Keptn to be able to add scrape jobs with the Keptn CLI or API.

**Comment by christian-kreuzberger-dtx** [comment]
> But this means that the command keptn configure monitoring prometheus --project=x --service=y is rendered useless

correct.

> I would like to configure an (external) Prometheus with Keptn to be able to add scrape jobs with the Keptn CLI or API.

Also correct -> #53.

I'm closing this issue in favour of #53.
