### ISSUE TITLE
Upgrade Prometheus installation

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/prometheus-service#50]
Currently the service is using Prometheus 2.12.0, but 2.18 is already available and 2.19 will be later this week. 
https://github.com/prometheus/prometheus/blob/master/RELEASE.md

Can we upgrade the installer to use newer versions of Prometheus?

Probably can we even use the Prometheus operator to install Prometheus and therefore we don't have to deal with all the manifests that we currently have to maintain?

**Comment by agrimmer** [comment]
As described here https://github.com/keptn-contrib/prometheus-service/issues/49, Keptn should not be responsible for properly setting up Prometheus.

**Comment by christian-kreuzberger-dtx** [comment]
While I agree with @agrimmer, we should make the exception right now and upgrade the version we ship right now.

**Comment by jetzlstorfer** [comment]
This will probably be handled with #53 (as this will use a user-managed prometheus instance)

**Comment by christian-kreuzberger-dtx** [comment]
This is no longer valid. Users are handling prometheus isntallation themselves via helm chart.
