### ISSUE TITLE
Same keptn context for different problems

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/prometheus-service#60]
Alerts from the alertmanager are accidentally mapped to the same Keptn context. This means that once a problem of type X is sent from the alertmanager to Keptn, all subsequent problems of type X will show up beneath the same root context, which is misleading. 

![image](https://user-images.githubusercontent.com/7677092/90607297-53faa000-e201-11ea-9fd5-e613a15e81ad.png)

As can be seen in the screenshot, a new problem was opened but it is shown as the same problem in Keptn.
Even worse, a couple of hours later a new problem was opened and remediated but I couldn't find it in the bridge since it was shown in the quite old problem root event.

![image](https://user-images.githubusercontent.com/7677092/90607452-83111180-e201-11ea-997d-254f57047f4d.png)

**Expected behavior**:
New problems are shown as new problems in the left-hand side of the bridge.

**Comment by christian-kreuzberger-dtx** [comment]
Confirming, this also happens in version 0.4.0.

**Comment by christian-kreuzberger-dtx** [comment]
Verified, this is still a problem.
I also am working on a fix.
