### ISSUE TITLE
Allow configuration of metrics endpoint for scrape jobs

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-contrib/prometheus-service#69]
Currently, the `prometheus-service` scrapes all metrics from the `/prometheus` endpoint of each service it monitors. 
However, the endpoint might not be available in each microservice.

Desired behavior: 
- [x] Allow custom metric endpoint to be configured, e.g., `/metrics` as environment variable (default is `/metrics`) 
- [x] Change service to scrap metrics from the configured endpoint 
- [ ] Adapt the examples (keptn/examples) to expose metrics on `/metrics` and not on `/prometheus`

**Comment by jetzlstorfer** [comment]
Most probably, the corresponding property in the code is this:

https://github.com/keptn-contrib/prometheus-service/blob/master/eventhandling/configureEvent.go#L650

**Comment by christian-kreuzberger-dtx** [comment]
We will most likely need a configuration file for this, so we can configure the prometheus endpoint per service.

**Comment by johannes-b** [comment]
I agree with @christian-kreuzberger-dtx, let us think of a `prometheus.conf.yaml` like: 

```
config:
  metrics-endpoint: "\metrics"
```

This file lives in the repo for each service in the folder: `SERVICE/prometheus/prometheus.conf.yaml`

**Comment by jetzlstorfer** [comment]
@warber 
Was the configuration file also introduced or is it done via an environment variable?
